### ISSUE TITLE
Add Channel to Toys Search

### ISSUE THREAD

**Issue by jgarte** [cdo256/cdo-guix-channel#1]
Hi,

Can we add your channel to the toys search?

https://toys.whereis.みんな/

**Comment by cdo256** [comment]
Hi,

Sure, there's not much to see here though!

The one that's more up to date is at https://git.mutix.org/cdo/guix-channel

**Comment by jgarte** [comment]
Still cool! :)

Here are the instructions for joining:

https://git.sr.ht/~whereiseveryone/toys#join

TLDR:

You would just need to add a `toys-box` record instance with your `cdo-guix-channel` information and send a patch for it.

**Comment by cdo256** [comment]
Done. Thanks!
